openapi: 3.0.0
info:
  title: RAG Content API
  description: API for indexing and retrieving educational content about ROS 2
  version: 1.0.0

paths:
  /content/index:
    post:
      summary: Index educational content
      description: Submit content for indexing in the RAG system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentChunk'
      responses:
        '200':
          description: Content successfully indexed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  chunkId:
                    type: string
                    example: "chunk-12345"
        '400':
          description: Invalid content format

  /content/search:
    post:
      summary: Search educational content
      description: Search for relevant content based on query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Search query
                  example: "How to connect Python agents to ROS 2"
                context:
                  type: string
                  enum: [full_book, selected_text]
                  description: Search context
                  default: "full_book"
                maxResults:
                  type: integer
                  description: Maximum number of results to return
                  default: 5
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResult'
        '400':
          description: Invalid search parameters

  /content/validate:
    post:
      summary: Validate content for RAG indexing
      description: Check if content is properly formatted for RAG system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentChunk'
      responses:
        '200':
          description: Validation results
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: boolean
                  issues:
                    type: array
                    items:
                      type: string

components:
  schemas:
    ContentChunk:
      type: object
      required:
        - id
        - title
        - content
        - metadata
      properties:
        id:
          type: string
          description: Unique identifier for the content chunk
        title:
          type: string
          description: Title of the content chunk
        content:
          type: string
          description: The actual content to be indexed
        metadata:
          type: object
          description: Metadata about the content
          properties:
            chapter:
              type: string
              description: Chapter this content belongs to
            section:
              type: string
              description: Section within the chapter
            difficulty:
              type: string
              enum: [beginner, intermediate]
              description: Difficulty level
            concepts:
              type: array
              items:
                type: string
              description: Key concepts covered in the content
            targetAudience:
              type: array
              items:
                type: string
              description: Target audience for this content

    SearchResult:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the result
        title:
          type: string
          description: Title of the content
        content:
          type: string
          description: Relevant content snippet
        source:
          type: string
          description: Source location of the content
        relevance:
          type: number
          format: float
          description: Relevance score (0-1)